spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_boot_intro?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: 'root'
        password:
    jpa:
        # Choose either MySQL 8 or MySQL 5 below
        # For MySQL 5:
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        # For MySQL 8:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
